services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=devduel
    volumes:
      - ./data:/var/lib/postgresql
    ports:
      - 5432:5432
