#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Format all files
pnpm format

# Run next build and check if it fails
npm run build

# If build fails, stop commit
if [ $? -ne 0 ]; then
  echo "Build failed, commit stopped"
  exit 1
fi



